<a href="https://colab.research.google.com/github/BlazeIngithub/BlazeIngithub/blob/main/00_Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
print("Hello! I am excited to lean Pytorch")

Hello! I am excited to lean Pytorch


PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.



In [2]:
print("00_Pytorch_fundamentals.ipynb")

00_Pytorch_fundamentals.ipynb


#Torch
The torch package contains data structures for multi-dimensional tensors and defines mathematical operations over these tensors. Additionally, it provides many utilities for efficient serialization of Tensors and arbitrary types, and other useful utilities.


It has a CUDA counterpart, that enables you to run your tensor computations on an NVIDIA GPU with compute capability >= 3.0.







In [3]:
#Let import some of the libraries first

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [4]:
#Introductions to tensors
#Scaler
scaler= torch.tensor(7)
scaler



tensor(7)

In [5]:
scaler.ndim #dimensions

0

In [6]:
#get
scaler.item()

7

In [7]:
#vector
vector= torch.tensor([7, 7]) #vector usally has magnitude and direction

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#Matrix
matrix= torch.tensor([[7,8],
                     [5,6]])
matrix

tensor([[7, 8],
        [5, 6]])

In [11]:
matrix.ndim

2

In [12]:
matrix[0] #we can check the index

tensor([7, 8])

In [13]:
matrix.shape

torch.Size([2, 2])

In [14]:
TENSOR= torch.tensor([[[1, 2, 3,],
                       [4,5,6],
                       [6,7,8]]])
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

###Random tensor

Random tensor are important because the way many neural network learn is a that they start start with tensors full of random number and then adjust those random number to better represent the data

start with random numner -> look at data -> update random number -> look at the data-> update

In [16]:
###Random tensor

random_tensor= torch.rand(3,4)
random_tensor

tensor([[0.1974, 0.0049, 0.8198, 0.1872],
        [0.5291, 0.7413, 0.9932, 0.2097],
        [0.8173, 0.1335, 0.3274, 0.2738]])

In [17]:
random_tensor.ndim #dimensions

2

In [18]:
#random tensor with similar shape to image tensor

random_image_size_tensor= torch.rand(size=(224, 224, 3)) #Height, width, color channels(R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
# zeroes and ones tensor

zeros= torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones= torch.ones(5,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

##range

In [21]:
one_to_nine = torch.arange(1,50, 5)
print(one_to_nine)

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])


In [22]:
#creating tensor like
one_to_ten= torch.zeros_like(one_to_nine)
one_to_ten

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##Tensor datatypes

Note: Tensor datatypes is one of the 3 big errors you'll run into Pytorch or deep learning
1. Tensor are not right dtype
2. Tensor are not right shape
3. Tensor not on the right device

In [23]:
float_32_tensor= torch.tensor([3.0, 5.0, 6.0],
                              dtype=None, #hat datatype is the tensor
                              device=None,#what device is your tensor is on
                              requires_grad=False) #Autograd
float_32_tensor.dtype

torch.float32

In [24]:
int_32_tensor= torch.tensor([2,3,4], dtype=torch.int32)
int_32_tensor


tensor([2, 3, 4], dtype=torch.int32)

In [25]:
float_32_tensor *int_32_tensor


tensor([ 6., 15., 24.])

##Manipulating tensor
- Add
-subtract
-multiply
-divide






In [26]:
tensor= torch.tensor([3, 5])
tensor

tensor([3, 5])

In [27]:
  tensor+10  #adding to 10 to tensor

tensor([13, 15])

In [28]:
tensor-10 #subtracting 10 from tensor

tensor([-7, -5])

In [29]:
tensor*10 #multiply

tensor([30, 50])

In [30]:
tensor/10 #Divide

tensor([0.3000, 0.5000])

##Matrix multiplications

In [31]:
#Element wise multiplication
print( tensor, "*" ,tensor)
print(f"Equals: {tensor*tensor}")

tensor([3, 5]) * tensor([3, 5])
Equals: tensor([ 9, 25])


In [32]:
#Matrix multiplication
%%time
torch.matmul(tensor, tensor)

CPU times: user 128 µs, sys: 855 µs, total: 983 µs
Wall time: 9.74 ms


tensor(34)

In [33]:
#matrix multiplication by hand

3*3 + 5* 5

34

In [34]:
%%time
value=0
for i in range(len(tensor)):
  value+= tensor[i] * tensor[i]
print(value)

tensor(34)
CPU times: user 1.88 ms, sys: 0 ns, total: 1.88 ms
Wall time: 1.82 ms


##there are two main rules that performing matrix multiplication needs to satisfy
1. the **inner dimensions** must match
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of the **outer dimension**:

In [35]:
# example
torch.matmul(torch.rand(3,2),torch.rand(2, 3)) #multiplied

tensor([[0.6455, 0.4260, 0.3398],
        [0.9909, 0.6694, 0.5517],
        [1.0090, 0.5715, 0.3471]])

In [36]:
torch.matmul(torch.rand(3,2),torch.rand(3, 2)) #error

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [37]:
#transpose

tensor = torch.rand(4,3)
tensor, tensor.T #matrix transpose

(tensor([[0.1750, 0.4080, 0.3555],
         [0.1219, 0.9899, 0.2785],
         [0.9750, 0.7253, 0.3494],
         [0.6260, 0.0603, 0.3479]]),
 tensor([[0.1750, 0.1219, 0.9750, 0.6260],
         [0.4080, 0.9899, 0.7253, 0.0603],
         [0.3555, 0.2785, 0.3494, 0.3479]]))

In [38]:
tensor.shape, tensor.T.shape

(torch.Size([4, 3]), torch.Size([3, 4]))

###Finding min, max, mean, sum, etc (tensor aggregation)

In [41]:
#create a tensor

x= torch.arange(1, 10, 2)
x

tensor([1, 3, 5, 7, 9])

In [43]:
#find the max
torch.max(x), x.max()

(tensor(9), tensor(9))

In [45]:
#find min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [48]:
#find mean- note: the torch.mean() function requires a tensor of float32 datatype to work

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(5.), tensor(5.))

In [49]:
#find sum
torch.sum(x), x.sum()

(tensor(25), tensor(25))

###Finding the positional min and max

In [50]:
x

tensor([1, 3, 5, 7, 9])

In [51]:
#find the position in tensor that has the minimum value with argmin()->return index position of target tensor where min value accurs

x.argmin()

tensor(0)

In [52]:
x[0]

tensor(1)

In [53]:
x.argmax()

tensor(4)

In [55]:
x[4]

tensor(9)