<a href="https://colab.research.google.com/github/BlazeIngithub/BlazeIngithub/blob/main/00_Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
print("Hello! I am excited to lean Pytorch")

Hello! I am excited to lean Pytorch


PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.



In [46]:
print("00_Pytorch_fundamentals.ipynb")

00_Pytorch_fundamentals.ipynb


#Torch
The torch package contains data structures for multi-dimensional tensors and defines mathematical operations over these tensors. Additionally, it provides many utilities for efficient serialization of Tensors and arbitrary types, and other useful utilities.


It has a CUDA counterpart, that enables you to run your tensor computations on an NVIDIA GPU with compute capability >= 3.0.







In [47]:
#Let import some of the libraries first

import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


In [48]:
#Introductions to tensors
#Scaler
scaler= torch.tensor(7)
scaler



tensor(7)

In [49]:
scaler.ndim #dimensions

0

In [50]:
#get
scaler.item()

7

In [51]:
#vector
vector= torch.tensor([7, 7]) #vector usally has magnitude and direction

In [52]:
vector.ndim

1

In [53]:
vector.shape

torch.Size([2])

In [54]:
#Matrix
matrix= torch.tensor([[7,8],
                     [5,6]])
matrix

tensor([[7, 8],
        [5, 6]])

In [55]:
matrix.ndim

2

In [56]:
matrix[0] #we can check the index

tensor([7, 8])

In [57]:
matrix.shape

torch.Size([2, 2])

In [58]:
TENSOR= torch.tensor([[[1, 2, 3,],
                       [4,5,6],
                       [6,7,8]]])
TENSOR.ndim

3

In [59]:
TENSOR.shape

torch.Size([1, 3, 3])

###Random tensor

Random tensor are important because the way many neural network learn is a that they start start with tensors full of random number and then adjust those random number to better represent the data

start with random numner -> look at data -> update random number -> look at the data-> update

In [60]:
###Random tensor

random_tensor= torch.rand(3,4)
random_tensor

tensor([[0.4772, 0.7602, 0.6051, 0.9993],
        [0.2919, 0.3572, 0.9914, 0.2249],
        [0.5795, 0.8638, 0.1386, 0.8771]])

In [61]:
random_tensor.ndim #dimensions

2

In [62]:
#random tensor with similar shape to image tensor

random_image_size_tensor= torch.rand(size=(224, 224, 3)) #Height, width, color channels(R, G, B)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [63]:
# zeroes and ones tensor

zeros= torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [64]:
ones= torch.ones(5,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

##range

In [65]:
one_to_nine = torch.arange(1,50, 5)
print(one_to_nine)

tensor([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])


In [66]:
#creating tensor like
one_to_ten= torch.zeros_like(one_to_nine)
one_to_ten

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##Tensor datatypes

Note: Tensor datatypes is one of the 3 big errors you'll run into Pytorch or deep learning
1. Tensor are not right dtype
2. Tensor are not right shape
3. Tensor not on the right device

In [67]:
float_32_tensor= torch.tensor([3.0, 5.0, 6.0],
                              dtype=None, #hat datatype is the tensor
                              device=None,#what device is your tensor is on
                              requires_grad=False) #Autograd
float_32_tensor.dtype

torch.float32

In [68]:
int_32_tensor= torch.tensor([2,3,4], dtype=torch.int32)
int_32_tensor


tensor([2, 3, 4], dtype=torch.int32)

In [69]:
float_32_tensor *int_32_tensor


tensor([ 6., 15., 24.])

##Manipulating tensor
- Add
-subtract
-multiply
-divide






In [70]:
tensor= torch.tensor([3, 5])
tensor

tensor([3, 5])

In [71]:
  tensor+10  #adding to 10 to tensor

tensor([13, 15])

In [72]:
tensor-10 #subtracting 10 from tensor

tensor([-7, -5])

In [73]:
tensor*10 #multiply

tensor([30, 50])

In [74]:
tensor/10 #Divide

tensor([0.3000, 0.5000])

##Matrix multiplications

In [75]:
#Element wise multiplication
print( tensor, "*" ,tensor)
print(f"Equals: {tensor*tensor}")

tensor([3, 5]) * tensor([3, 5])
Equals: tensor([ 9, 25])


In [76]:
#Matrix multiplication
%%time
torch.matmul(tensor, tensor)

CPU times: user 67 µs, sys: 10 µs, total: 77 µs
Wall time: 81.8 µs


tensor(34)

In [77]:
#matrix multiplication by hand

3*3 + 5* 5

34

In [78]:
%%time
value=0
for i in range(len(tensor)):
  value+= tensor[i] * tensor[i]
print(value)

tensor(34)
CPU times: user 645 µs, sys: 105 µs, total: 750 µs
Wall time: 769 µs


##there are two main rules that performing matrix multiplication needs to satisfy
1. the **inner dimensions** must match
* (3, 2) @ (3, 2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of the **outer dimension**:

In [79]:
# example
torch.matmul(torch.rand(3,2),torch.rand(2, 3)) #multiplied

tensor([[0.2659, 0.3540, 0.7529],
        [0.1775, 0.2207, 0.4160],
        [0.0744, 0.1440, 0.4605]])

In [80]:
#torch.matmul(torch.rand(3,2),torch.rand(3, 2)) #error

In [81]:
#transpose

tensor = torch.rand(4,3)
tensor, tensor.T #matrix transpose

(tensor([[0.6350, 0.2890, 0.0182],
         [0.2981, 0.3164, 0.9494],
         [0.8357, 0.9965, 0.6357],
         [0.0147, 0.0184, 0.8973]]),
 tensor([[0.6350, 0.2981, 0.8357, 0.0147],
         [0.2890, 0.3164, 0.9965, 0.0184],
         [0.0182, 0.9494, 0.6357, 0.8973]]))

In [82]:
tensor.shape, tensor.T.shape

(torch.Size([4, 3]), torch.Size([3, 4]))

###Finding min, max, mean, sum, etc (tensor aggregation)

In [83]:
#create a tensor

x= torch.arange(1, 10, 2)
x

tensor([1, 3, 5, 7, 9])

In [84]:
#find the max
torch.max(x), x.max()

(tensor(9), tensor(9))

In [85]:
#find min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [86]:
#find mean- note: the torch.mean() function requires a tensor of float32 datatype to work

torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(5.), tensor(5.))

In [87]:
#find sum
torch.sum(x), x.sum()

(tensor(25), tensor(25))

###Finding the positional min and max

In [88]:
x

tensor([1, 3, 5, 7, 9])

In [89]:
#find the position in tensor that has the minimum value with argmin()->return index position of target tensor where min value accurs

x.argmin()

tensor(0)

In [90]:
x[0]

tensor(1)

In [91]:
x.argmax()

tensor(4)

In [92]:
x[4]

tensor(9)

###Reshaping, stacking, squeezing, and unsquezing

*Reshaping - reshapes an input tensor to define shape*

*View- Return a view of an input tensor of certain shape but keep the same memory as the original tensor*

*Stacking- Combine multiple tensore on the top of each other (vstack) or side by side(hstack)*
*Squeeze- remove all '1' dimensions from tensors*
*unsqueeze- add a '1' dimensions to a target tensors*
*Permute - Return a way of input with dimension permuted(swapped) in a certain way*

In [93]:
#let's create a tensor

x= torch.arange(1.0, 10.0 )
x

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [94]:
#Add extra dimension
x_reshaped= x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [95]:
#Add extra dimension
x_reshaped= x.reshape(3, 3)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [96]:
#change the view

z= x.view(9,1)#doing teh same thing
z, z.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [97]:
z= x.view(1,9)#doing teh same thing
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [98]:
#Changing z changes x(because a view of a tensor share the same memory as the original

z[ : , 0] =5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [100]:
#stack tensor at the top
x_stacked = torch.stack([x, x, x, x], dim=0) #vstack
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [101]:
  #stack tensor at the top
x_stacked = torch.stack([x, x, x, x], dim=1) #hstack
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [105]:
#torch.squeeze
x_reshaped
x_reshaped.shape

torch.Size([3, 3])

In [104]:
x_reshaped.squeeze(), x_reshaped.squeeze().shape

(tensor([[5., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

In [109]:
y= torch.tensor([[1, 9]])
y

tensor([[1, 9]])

In [111]:
y_squeezed=  y.squeeze()#squeeze 2 dimension in one
y_squeezed

tensor([1, 9])

In [115]:
#torch.unsqueeze()

y_unsqueezed= y_squeezed.unsqueeze(dim=1)
y_unsqueezed

tensor([[1],
        [9]])

In [123]:
#torch.permute-> Returns a view of the original tensor input with its dimensions permuted.
x_original= torch.rand(size= (224, 224, 3)) #[height, width, color_channel]
x_original.shape
#permute to orginal tensor to rearrange the axis(or dim) order

x_permuted= x_original.permute(2, 0, 1) #shift axis 0->1, 1->2, 2->0)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

##Indexing

Indexing in pytorch is similar to indexing in numpy





In [125]:
#Create a tensor
import torch
x= torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape


(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [127]:
#let's index on our new tensor

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [129]:
#let's index on middle bracket

x[0, 0]

tensor([1, 2, 3])

In [132]:
#let's index on most inner bracket
x[0,0,0], x[0,0,1], x[0,0,2]

(tensor(1), tensor(2), tensor(3))

In [137]:
#let's get number 9

x[0, 2, 2]

tensor(9)

In [139]:
# You can also use ":" to select all the target dimensions

x[: ,0]

tensor([[1, 2, 3]])

In [146]:
x[:,:,0]

tensor([[1, 4, 7]])

In [147]:
x[:,2,]

tensor([[7, 8, 9]])

In [150]:
#get all values of  0th dimension  but only index 1 of 2nd dimension
x[:, 1, 1]

tensor([5])

In [151]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [176]:
x[0,1:, 1:2]

tensor([[5],
        [8]])

  ## Pytorch tensor and **numpy**

  Numpy is a popular scientific python numerical computing library.

  And because of this, pytorch has functionality to interact with it.

  *Data in Numypy, want in Pytorch tensor ->torch.from_numpy(ndarry)
  
  *Pytorch tensor -> Numpy -> torch.tensor.numpy()


In [186]:
#Numpy array to tensor

import torch
import numpy as np

array= np.arange(1.0, 8.0)
array
tensor= torch.from_numpy(array) #warning -> when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [187]:
#Change the value of array, what will this do to tensor
array= array+1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [194]:
  #Tensor to numpy

tensor= torch.ones(7)
tensor
numpy_tensor=tensor.numpy()
type(numpy_tensor), numpy_tensor

(numpy.ndarray, array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [196]:
#change the tensor, what happens to numpy tensor
tensor= tensor+1

In [198]:
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility(trying to take random out of random)

In short how a neaural network learns
start with random numbers -> tensor operations -> update random numbers to try and make them better representations of data -> again -> again...

To reduce the randomness in neaural network and pytorch comes the concept of a random seed.

Essentially what a random seed does is "flavour" the randomness



In [203]:
#create 2 random tensors
random_tensor_A= torch.rand(3, 3)
random_tensor_B= torch.rand(3, 3)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.3955, 0.9730, 0.5084],
        [0.4199, 0.0431, 0.0489],
        [0.4111, 0.0048, 0.0264]])
tensor([[0.6212, 0.0162, 0.9361],
        [0.1033, 0.1821, 0.1054],
        [0.5845, 0.4985, 0.9426]])
tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])


In [205]:
#Let's make some random but reproducible tensors

import torch

#set the random seed

RANDOM_SEED= 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C= torch.rand(3, 4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D= torch.rand(3, 4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##Running tensors and pytorch objects on GPUs(making faster computation)
GPU= faster computution on numbers

pytorch + GPU drivers(cuda) takes a little bit of setting up, to do this, refer to pytorch setup documentation

https://pytorch.org/get-started/locally/?ajs_aid=813eb3b6-61a7-4483-81d9-fc815bc2c1e9


In [206]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [207]:
import torch
print(torch.cuda.is_available())  # True if GPU is enabled


False


In [209]:
#Device agnostic code

device= "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'